### PR TITLE
V1400

### PR DESCRIPTION
**Pull request by raghu-madat**

### CODE REVIEW

**Comment by vickum** [comment]
looks fine to me.

**Review by saravananbalakris — APPROVED** [review]
Looks fine to me

**Review by vickum — CHANGES_REQUESTED** [review]
It seems one change is still left out for "nif.c" file for "misc\nif" sample. Please remove #include <lapiplat.h> form there and recompile.

**Review by vickum — APPROVED** [review]
The concern raised by me is resolved now in this PR
https://github.com/HCL-TECH-SOFTWARE/domino-c-api-samples/pull/45

**Pull request merged**
